version: "3.3"

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  # SMTP Server
  mail:
    image: boky/postfix
    container_name: postfix
    restart: always
    environment:
      - "ALLOWED_SENDER_DOMAINS=doitand711gang.cse356.compas.cs.stonybrook.edu"
      - "MYNETWORKS=130.245.136.0/24"
    network_mode: "host"

  # NodeJS
  node:
    container_name: node
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src # Mount your local directory to the container
      - ./media:/app/media # Mounting the mounted volume to the container.
      - ./padded_videos:/app/padded_videos
      - ./videos:/app/videos
    env_file:
      - .env
    depends_on:
      - mail
      - mongodb

  # Redis for Gorse
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  # MySQL for Gorse
  mysql:
    container_name: mysql
    image: mysql/mysql-server
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: gorse
      MYSQL_USER: gorse
      MYSQL_PASSWORD: gorse_pass

  # Gorse (Recommender System)
  gorse:
    container_name: gorse
    image: zhenghaoz/gorse-in-one
    restart: unless-stopped
    ports:
      - 8086:8086 # gRPC port
      - 8088:8088 # HTTP port
    environment:
      # Use Redis as cache storage backend.
      GORSE_CACHE_STORE: redis://redis:6379
      # Use MySQL as data storage backend.
      GORSE_DATA_STORE: mysql://gorse:gorse_pass@tcp(mysql:3306)/gorse?parseTime=true
    command: >
      -c /etc/gorse/config.toml 
      --log-path /var/log/gorse/master.log 
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      # Mount the configuration file.
      - ./config.toml:/etc/gorse/config.toml
    depends_on:
      - redis
      - mysql

volumes:
  mongo-data:
