# version: "3.8"

services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy/worker.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 80:80
  # NodeJS
  node:
    # container_name: node
    build: .
    # ports:
    #   - "80:80"
    volumes:
      - ./src:/app/src # Mount your local directory to the container
      # - /mnt/media:/app/media # Mounting the mounted volume to the container.
      # - ./media:/app/media 
      # - ./padded_videos:/app/padded_videos
      # - ./videos:/app/videos
    env_file:
      - .env