# version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    volumes: 
      - ./nginx/node-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80 # Reverse Proxying Node
  # NodeJS
  node:
    # container_name: node
    build: .
    # ports:
    #   - "80:80"
    volumes:
      - ./src:/app/src # Mount your local directory to the container
      - /mnt/media:/app/media # Mounting the mounted volume to the container.
      # - ./media:/app/media 
      - ./padded_videos:/app/padded_videos
      - ./videos:/app/videos
    env_file:
      - .env