services:
# MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # Scale up Mongodb
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: