version: "3.3"
services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  mail:
    image: boky/postfix
    container_name: postfix
    restart: always
    environment:
      - "ALLOWED_SENDER_DOMAINS=doitand711gang.cse356.compas.cs.stonybrook.edu"
      - "MYNETWORKS=130.245.136.0/24"

    network_mode: "host"

  # NodeJS
  node:
    container_name: node
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/app # Mount your local directory to the container
      - /app/node_modules 
    networks:
      - app-network
    env_file:
      - .env

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
