project_dir: /root/cse356-project/
- name: Set up Express
  hosts: node
  become: yes
  become_method: sudo
  remote_user: root

  tasks:
    - import_tasks: tasks/installDocker.yaml
    - import_tasks: task/cloneRepository.yaml
    - name: Compose Down 
      ansible.builtin.command: docker compose -f {{project_dir}}/docker-compose.yml down

    - name: Compose Express
      ansible.builtin.command: docker compose -f {{project_dir}}/docker-compose.yml up

