- name: Set up MongoDB
  hosts: mongo
  vars_files:
    - vars/main.yaml
  become: yes
  become_method: sudo
  remote_user: root

  tasks:
    - import_tasks: tasks/installDocker.yaml
    - import_tasks: tasks/cloneRepository.yaml
    - name: Compose Down 
      ansible.builtin.command: docker compose -f {{project_dir}}/mongoDB/docker-compose.yml down

    - name: Compose Nginx, Prometheus, ffmpeg-queue
      ansible.builtin.command: docker compose -f {{project_dir}}/mongoDB/docker-compose.yml up

