project_dir: /root/cse356-project/mongoDB
- name: Set up MongoDB
  hosts: mongo
  become: yes
  become_method: sudo
  remote_user: root

  tasks:
    - import_tasks: tasks/installDocker.yaml
    - import_tasks: task/cloneRepository.yaml
    - name: Compose Down 
      ansible.builtin.command: docker compose -f {{project_dir}}/docker-compose.yml down

    - name: Compose Nginx, Prometheus, ffmpeg-queue
      ansible.builtin.command: docker compose -f {{project_dir}}/docker-compose.yml up

